// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    // SECCIÓN: BIENVENIDA
    {
      type: "category",
      label: "Primeros Pasos",
      className: "category-as-header getting-started-header",
      collapsed: false,
      collapsible: false,
      items: [
        "doc-home-page",
      ],
    },

    // SECCIÓN: PLATFORM ENGINEERING (Aquí CKA)
    {
      type: "category",
      label: "Ingeniería de Plataforma",
      className: "category-as-header platform-engineering-header",
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "platform-engineering",
        },
      ],
    },

    // SECCIÓN: DATA ENGINEERING (Cloudera)
    {
      type: "category",
      label: "Ingeniería de Datos",
      className: "category-as-header data-sources-header",
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "data-engineering",
        },
      ],
    },

    // highlight-start
    // SECCIÓN: SYSADMIN & LINUX (Configuración de base)
    {
      type: "category",
      label: "SysAdmin & Linux",
      className: "category-as-header sysadmin-linux-header", // Clase para estilo visual consistente
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "sysadmin-linux",
        },
      ],
    },
    // highlight-end

    // SECCIÓN: ESTÁNDARES
    {
      type: "category",
      label: "Estándares de Ingeniería",
      className: "category-as-header engineering-stds-header",
      collapsed: false,
      collapsible: false,
      items: [
	{
          type: "autogenerated",
          dirName: "engineering-standards",
        },
      ],
    },
  ],
};

module.exports = sidebars;
