# Nombre del flujo de trabajo
name: Deploy website to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Trabajo de construcción
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # ¡CAMBIO IMPORTANTE! Necesario para que clone el theme Stack
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # Puedes fijar una versión o usar 'latest'
          hugo-version: 'latest' 
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

          #      - name: Build with Hugo
          #        env:
          #          # Esta variable asegura que Hugo construya el sitio para producción
          #          HUGO_ENVIRONMENT: production
          #        run: |
          #          # El comando 'hugo' por sí solo es suficiente. La baseURL se gestiona automáticamente
          #          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          # Usa la baseURL definida en hugo.yaml
          hugo --minify






      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Trabajo de despliegue (este no cambia en absoluto)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
